/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mancuso.aoc2020;

public class Day2 extends AbstractDay {
    public String name() {
        return "Day2";
    }

    public String part1() {
        return null;
    }

    public String part2() {
        return null;
    }

    public static void main(String[] args) {
        Day2 app = new Day2();
        app.run();
        app.report();
    }
}
