/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mancuso.aoc2020.app;

import org.mancuso.aoc2020.*;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List<AbstractDay> days = new ArrayList<>();
        String pkgName = "org.mancuso.aoc2020.";
        for (int i = 1; i < 25; i++) {
            String shortName = "Day" + i;
            String dayName = pkgName + shortName;
            try {
                Class<? extends AbstractDay> clazz = (Class<? extends AbstractDay>) Class.forName(dayName);
                var constructor = clazz.getConstructor();
                days.add(constructor.newInstance());
            } catch (ClassNotFoundException ex) {
                System.out.println(shortName + " not implemented");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        for (AbstractDay day : days) {
            try {
                day.run();
            } catch (Throwable ex) {
                System.out.println("Exception on day " + day.name() + ": " + ex.getMessage());
            }
        }
        for (AbstractDay day : days) {
            System.out.println(day.report());
        }
    }
}
