/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mancuso.aoc2020.app;

import org.mancuso.aoc2020.*;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List<AbstractDay> days = new ArrayList<>();
        days.add(new Day1());
        days.add(new Day2());
        days.add(new Day3());
        days.add(new Day4());
        days.add(new Day5());
        days.add(new Day6());
        days.add(new Day7());
        days.add(new Day8());
        days.add(new Day9());
        for (AbstractDay day : days) {
            try {
                day.run();
            } catch(Throwable ex) {
                System.out.println("Exception on day " + day.name()+": " +  ex.getMessage());
            }
        }
        for (AbstractDay day : days) {
            System.out.println(day.report());
        }
    }
}
