/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mancuso.aoc2020;

import org.junit.Test;
import static org.junit.Assert.*;

public class Day2Test {
    @Test public void testAppHasAGreeting() {
        Day2 classUnderTest = new Day2();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
